### ISSUE TITLE
Broken link to yellow paper

### ISSUE THREAD

**Issue by abchrisxyz** [ergoplatform/awesome-ergo#9]
In the [docs](https://github.com/ergoplatform/awesome-ergo/blob/master/pages/docs.md) page:

```
- [Yellow paper (in progress)](https://docs.ergoplatform.com/YellowPaper.pdf)
```

https://ergoplatform.org/docs/YellowPaper.pdf gives a 403.

**Comment by glasgowm148** [comment]
I have moved this to http://docs.ergoplatform.org now (pasted into respective categories). Can also be found on the main ergo repository in Latex form.
